learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/config/routes.rb
Rails.application.routes.draw do

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end
  

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'

  # get ':controller(/:action(/:id))'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # custom table name
  # self.table_name = "admin_users"

  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/page.rb
class Page < ApplicationRecord

  # belongs_to :subject, { :foreign_key => 'subject_id' }
  # belongs_to :subject, { :optional => true }  // turn on validation
  belongs_to :subject, { :optional => false }
  has_many :sections
  has_and_belongs_to_many :admin_users

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/section.rb
class Section < ApplicationRecord

  belongs_to :page
  has_many :section_edits
  has_many :admin_users, :through => :section_edits

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("position ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  
  belongs_to :admin_user
  belongs_to :section

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

  scope :visible, lambda{ where(:visible => true) }
  scope :invisible, lambda{ where(:visible => false) }
  scope :sorted, lambda{ order("position ASC") }
  scope :newest_first, lambda{ order("created_at DESC") }
  scope :search, lambda{ |query| where(["name LIKE ?", "%#{query}%"]) }

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout 'application'

  def index
    render('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @page = params['page']
    @id = params['id']
    render('hello')
  end

  def other_hello
    redirect_to(:controller => 'demo', :action => 'index')
  end

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'admin'
  def index
    @pages = Page.sorted
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      flash[:notice] = "Page created successfully"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Page updated successfully"
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page updated successfully"
    redirect_to(pages_path)
  end

  private
  def page_params
    params.require(:page).permit(:name, :position, :visible, :subject_id, :permalink)
  end

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/controllers/sections_controller.rb
require 'pry'

class SectionsController < ApplicationController
  layout 'admin'
  def index
    @sections = Section.sorted

    # Set a page title, similar to ASP.NET ViewBag
    # @page_title = "All Sections"
  end

  def show
    # binding.pry
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    
    if @section.save
      flash[:notice] = "Section created successfully"
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice] = "Section updated successfully"
      redirect_to(section_path(@section))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section updated successfully"
    redirect_to(sections_path)
  end

  private
  def section_params
    params.require(:section).permit(:name, :position, :visible, :page_id, :content_type, :content)
  end

end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout 'admin'
  
  def index
    @subjects = Subject.sorted
    @page_title = "All Subjects"
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new(:name => 'Default')
  end

  def create
    # 1. Instantiate a new object using form parameters
    # @subject = Subject.new(params[:subject])
    @subject = Subject.new(subject_params)

    # 2. Save the object
    if @subject.save
      # 3. If save succeeds, redirect to the index action
      flash[:notice] = "Subject created successfully."
      redirect_to(subjects_path)
    else
      # 4. If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    # Find
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated successfully."
      # If successds, redirect to show
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end
  
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject '#{@subject.name}' destored successfully."
    redirect_to(subjects_path)
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/helpers/application_helper.rb
module ApplicationHelper
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/helpers/demo_helper.rb
module DemoHelper
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/helpers/pages_helper.rb
module PagesHelper
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/helpers/sections_helper.rb
module SectionsHelper
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/helpers/subjects_helper.rb
module SubjectsHelper
end

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/demo/hello.html.erb
<div>
  Page: <%= @page %>
</div>
<div>
  Id: <%= @id %>
</div>

<% @array.each do |n| %>
  <%= n %>
<% end %>

<%= link_to('Index', {:action => 'index'}) %>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/demo/index.html.erb
<h1>Hello</h1>
<a href="/demo/hello">Hello 1</a>
<%= link_to('Hello 2', {:action => 'hello', :page => 5, :id => 20}) %>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/layouts/_footer.html.erb
<div>Aaron Guo Studio </div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
  </div>
</nav>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS - <%= @page_title || "Admin Area" %></title>
  </head>
  <body>
    <% if !flash[:notice].blank? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="test-hover">
      Hover test
    </div>
    <!-- Before yield -->
    <%= yield %>
    <!-- After yield -->
  </body>
</html>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/_form.html.erb
<table>
  <tr>
    subject id: <td><%= f.text_field(:subject_id) %></td>
    name: <td><%= f.text_field(:name) %></td>
    permalink: <td><%= f.text_field(:permalink) %></td>
    position: <td><%= f.text_field(:position) %></td>
    visible: <td><%= f.text_field(:visible) %></td>
  </tr>
</table>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/delete.html.erb
<div>
  <%= link_to '< Back', pages_path, :class => 'back-link' %>
  <div>
  Are you sure delete this page?
  </div>
  <%= form_for(@page, :method => 'delete') do |f| %>
    <%= f.object.name %>
    <%= f.submit("Delete Page") %>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/edit.html.erb
<div class="pages index">
  <%= link_to '< Back', pages_path, :class => 'back-link' %>
  <h2>Update Page</h2>
  <%= form_for(@page) do |f| %>
    <%= render partial: 'form', locals: { :f => f } %>
    <div>
      <%= f.submit("Update Page") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/index.html.erb
<div class="pages index">
  <%= link_to 'New Page', new_page_path, :class => 'action new' %>
  <table>
    <% @pages.each do |page| %>
      <tr>
        <td style="width: 100px;"><%= page.subject.id %></td>
        <td style="width: 100px;"><%= page.name %></td>
        <td style="width: 100px;"><%= page.position %></td>
        <td style="width: 100px;">permalink <%= page.permalink %></td>
        <td style="width: 100px;"><%= page.visible ? 'Yes' : 'No' %></td>
        <td style="width: 100px;"><%= page.sections.size %></td>
        <td class="actions">
          <%= link_to 'Show', page_path(page), :class => 'action show' %>
          <%= link_to 'Edit', edit_page_path(page), :class => 'action edit' %>
          <%= link_to 'Delete', delete_page_path(page), :class => 'action delete' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/new.html.erb
<div class="pages index">
  <%= link_to '< Back', pages_path, :class => 'back-link' %>
  <h2>New Page</h2>
  <%= form_for(@page) do |f| %>
    <%= render partial: 'form', locals: { :f => f } %>  
    <div>
      <%= f.submit("Create Page") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/pages/show.html.erb
<div class="pages index">
  <%= link_to '< Back', pages_path, :class => 'back-link' %>
  <table>
    <tr>
      <td><%= @page.subject_id %></td>
      <td><%= @page.position %></td>
      <td><%= @page.name %></td>
      <td><%= @page.visible ? 'Yes' : 'No' %></td>
      <td><%= @page.sections.size %></td>
    </tr>
  </table>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/_form.html.erb
<table>
  <tr>
    section id: <td><%= f.text_field(:page_id) %></td>
    name: <td><%= f.text_field(:name) %></td>
    position: <td><%= f.text_field(:position) %></td>
    visible: <td><%= f.text_field(:visible) %></td>
    content_type: <td><%= f.text_field(:content_type) %></td>
    content: <td><%= f.text_field(:content) %></td>
  </tr>
</table>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/delete.html.erb
<div>
  <%= link_to '< Back', sections_path, :class => 'back-link' %>
  <div>
  Are you sure delete this section?
  </div>
  <%= form_for(@section, :method => 'delete') do |f| %>
    <%= f.object.name %>
    <%= f.submit("Delete Section") %>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/edit.html.erb
<div class="sections index">
  <%= link_to '< Back', sections_path, :class => 'back-link' %>
  <h2>Update Section</h2>
  <%= form_for(@section) do |f| %>
    <%= render partial: 'form', locals: { :f => f } %>
    <div>
      <%= f.submit("Update Section") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/index.html.erb
<% @page_title = "All Sections" %>

<div class="sections index">
  <%= link_to 'New Section', new_section_path, :class => 'action new' %>
  <table>
    <% @sections.each do |section| %>
      <tr>
        <td style="width: 100px;"><%= section.page.id %></td>
        <td style="width: 100px;"><%= section.name %></td>
        <td style="width: 100px;"><%= section.position %></td>
        <td style="width: 100px;"><%= section.content_type %></td>
        <td style="width: 100px;"><%= section.content %></td>
        <td style="width: 100px;"><%= section.visible ? 'Yes' : 'No' %></td>
        <td class="actions">
          <%= link_to 'Show', section_path(section), :class => 'action show' %>
          <%= link_to 'Edit', edit_section_path(section), :class => 'action edit' %>
          <%= link_to 'Delete', delete_section_path(section), :class => 'action delete' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/new.html.erb
<div class="sections index">
  <%= link_to '< Back', sections_path, :class => 'back-link' %>
  <h2>New Section</h2>
  <%= form_for(@section) do |f| %>
    <%= render partial: 'form', locals: { :f => f } %>
    <div>
      <%= f.submit("Create Section") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/sections/show.html.erb
<div class="sections index">
  <%= link_to '< Back', sections_path, :class => 'back-link' %>
  <table>
    <tr>
      <td><%= @section.page_id %></td>
      <td><%= @section.position %></td>
      <td><%= @section.name %></td>
      <td><%= @section.visible ? 'Yes' : 'No' %></td>
      <td><%= @section.content_type %></td>
      <td><%= @section.content %></td>
    </tr>
  </table>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/_form.html.erb
<table>
  <tr>
    <td><%= f.text_field(:name) %></td>
    <td><%= f.text_field(:position) %></td>
    <td><%= f.text_field(:visible) %></td>
  </tr>
</table>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/delete.html.erb
<div>
  <%= link_to '< Back', subjects_path, :class => 'back-link' %>
  <div>
  Are you sure delete this subject?
  </div>
  <%= form_for(@subject, :method => 'delete') do |f| %>
    <%# get object from form builder, @subject.name is also good %>
    <%= f.object.name %>
    <%= f.submit("Delete Subject") %>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/edit.html.erb
<div class="subjects index">  
  <h2>Update Subject</h2>
  <%= form_for(@subject) do |f| %>
    <%= render partial: 'form', locals: { :f => f } %>
    <div>
      <%= f.submit("Update Subject") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/index.html.erb
<% @page_title = "All Subjects" %>

<div class="subjects index">
  <%= link_to 'New Section', new_subject_path, :class => 'action new' %>
  <table>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.position %></td>
        <td><%= subject.name %></td>
        <td><%= subject.visible ? 'Yes' : 'No' %></td>
        <td><%= subject.pages.size %></td>
        <td class="actions">
          <%= link_to 'Show', subject_path(subject), :class => 'action show' %>
          <%= link_to 'Edit', edit_subject_path(subject), :class => 'action edit' %>
          <%= link_to 'Delete', delete_subject_path(subject), :class => 'action delete' %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/new.html.erb
<div class="subjects index">
  <%= link_to '< Back', subjects_path, :class => 'back-link' %>
  <h2>New Subject</h2>

  <%#=
    form_for(@subject, :url => subjects_path, :method => 'post') do |f|
  %>
  <%# This can be simplified as below %>
  <%= form_for(@subject) do |f| %>
    <%#= render partial: 'form', :locals => { :f => f }%>
    <%= render partial: 'form', locals: { :f => f } %>
    <div>
      <%= f.submit("Create Subject") %>
    </div>
  <% end %>
</div>

learning/ruby-on-rails/learn/lynda/ruby-on-rails/simple_cms/app/views/subjects/show.html.erb
<div class="subjects index">
  <%= link_to '< Back', subjects_path, :class => 'back-link' %>
  <table>
    <tr>
      <td><%= @subject.position %></td>
      <td><%= @subject.name %></td>
      <td><%= @subject.visible ? 'Yes' : 'No' %></td>
      <td><%= @subject.pages.size %></td>
      <td class="actions">
        
      </td>
    </tr>
  </table>
</div>